CREATE TABLE product_label (
    label_id INT GENERATED BY DEFAULT AS IDENTITY,
    source VARCHAR NOT NULL,
    source_product_name VARCHAR NOT NULL,
    source_product_id VARCHAR NOT NULL,
    source_label_url VARCHAR,
    PRIMARY KEY (label_id)
);
ALTER TABLE product_label OWNER TO cem_dev_25_rw_grp;

CREATE TABLE vocab_meddra_adverse_effect (
    meddra_id INT GENERATED BY DEFAULT AS IDENTITY,
    meddra_name VARCHAR NOT NULL,
    meddra_term_type VARCHAR NOT NULL,
    PRIMARY KEY (meddra_id)
);
ALTER TABLE vocab_meddra_adverse_effect OWNER TO cem_dev_25_rw_grp;

CREATE TABLE vocab_rxnorm_ingredient (
    rxnorm_id VARCHAR NOT NULL,
    rxnorm_name VARCHAR NOT NULL,
    rxnorm_term_type VARCHAR NOT NULL,
    PRIMARY KEY (rxnorm_id)
);
ALTER TABLE vocab_rxnorm_ingredient OWNER TO cem_dev_25_rw_grp;

CREATE TABLE vocab_rxnorm_product (
    rxnorm_id VARCHAR NOT NULL,
    rxnorm_name VARCHAR NOT NULL,
    rxnorm_term_type VARCHAR NOT NULL,
    PRIMARY KEY (rxnorm_id)
);
ALTER TABLE vocab_rxnorm_product OWNER TO cem_dev_25_rw_grp;

CREATE TABLE product_adverse_effect (
    product_label_id INTEGER,
    effect_id INT GENERATED BY DEFAULT AS IDENTITY,
    label_section VARCHAR NOT NULL,
    effect_meddra_id INTEGER,
    match_method VARCHAR NOT NULL,
    pred0 FLOAT,
    pred1 FLOAT,
    PRIMARY KEY (effect_id),
    FOREIGN KEY(product_label_id) REFERENCES product_label (label_id),
    FOREIGN KEY(effect_meddra_id) REFERENCES vocab_meddra_adverse_effect (meddra_id)
);
ALTER TABLE product_adverse_effect OWNER TO cem_dev_25_rw_grp;

CREATE TABLE product_to_rxnorm (
    label_id INTEGER NOT NULL,
    rxnorm_product_id VARCHAR NOT NULL,
    PRIMARY KEY (label_id, rxnorm_product_id),
    FOREIGN KEY(label_id) REFERENCES product_label (label_id),
    FOREIGN KEY(rxnorm_product_id) REFERENCES vocab_rxnorm_product (rxnorm_id)
);
ALTER TABLE product_to_rxnorm OWNER TO cem_dev_25_rw_grp;

CREATE TABLE vocab_rxnorm_ingredient_to_product (
    ingredient_id VARCHAR NOT NULL,
    product_id VARCHAR NOT NULL,
    PRIMARY KEY (ingredient_id, product_id),
    FOREIGN KEY(ingredient_id) REFERENCES vocab_rxnorm_ingredient (rxnorm_id),
    FOREIGN KEY(product_id) REFERENCES vocab_rxnorm_product (rxnorm_id)
);
ALTER TABLE vocab_rxnorm_ingredient_to_product OWNER TO cem_dev_25_rw_grp;
